### PR TITLE
[#592] Miscelaneous minor fixes

### LINKED ISSUE #592: Minor fixes after integration of Evolution agent

### PR DESCRIPTION
**Pull request by andre-senna**
Resolves #592

### CODE REVIEW

File: src/agents/evolution/QueryEvolutionProcessor.cc [hunk 1]
```diff
@@ -222,14 +228,23 @@ void QueryEvolutionProcessor::correlate_similar(shared_ptr<QueryEvolutionProxy>
                 return;
             }
             token = original_tokens[cursor++];
-            string value = correlation_query_answer->assignment.get(token);
+            if (token == "sentence3") {
```
Comment (arturgontijo) [inline src/agents/evolution/QueryEvolutionProcessor.cc:231]: Do we want this here?

Comment (andre-senna) [reply src/agents/evolution/QueryEvolutionProcessor.cc:231]: Actually no. But it's the better we can do for now. I'm still trying to figure out how to setup correlation query in order for it to work (i.e. in order for it to make evolution as a whole work) so it's pointless to refactor the command API (which is what's is supposed to be required to fix this code).

Comment (andre-senna) [reply src/agents/evolution/QueryEvolutionProcessor.cc:231]: This is a hard-wired attempt to make the current query in word-query-evolution client work. I just shared this to make sure we both are running evolution on the same code.

**Review by arturgontijo — APPROVED** [review]
